### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zhengs1989** [fmbiete/pgauditlogtofile#43]
the error is as follows：

[root@dbmsprd pgauditlogtofile-1.6.0]# make install USE_PGXS=1 
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -Wdiscarded-qualifiers -fPIC -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal -I/usr/include -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgauditlogtofile.o pgauditlogtofile.c
cc1: error: unrecognized command line option "-Wdiscarded-qualifiers"
make: *** [pgauditlogtofile.o] Error 1

-------------------
environment
os：Red Hat Enterprise Linux Server release 6.3 (Santiago)
db：PostgreSQL 10.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23), 64-bit
pgauditlogtofile：1.6.0

**Comment by fmbiete** [comment]
RHEL 6 is EOL since a long time ago. 
PostgreSQL 10 is also EOL.

If you must compile under that version edit the Makefile and remove the flag from 
```
PG_CFLAGS = -Wall -Wdiscarded-qualifiers
```
but with those versions I don't know if something else will fail. I strongly advise to upgrade to a supported version for both PostgreSQL and Red Hat.
